<?php

namespace Container0Mi7x6W;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFixturesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FixturesController' shared autowired service.
     *
     * @return \App\Controller\FixturesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FixturesController.php';

        $container->services['App\\Controller\\FixturesController'] = $instance = new \App\Controller\FixturesController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\FixturesController', $container));

        return $instance;
    }
}
