<?php

namespace ContainerXadhmz6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSyncDataCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SyncDataCommand' shared autowired service.
     *
     * @return \App\Command\SyncDataCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/SyncDataCommand.php';

        $container->privates['App\\Command\\SyncDataCommand'] = $instance = new \App\Command\SyncDataCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['App\\Controller\\DataCopyController'] ?? $container->load('getDataCopyControllerService')));

        $instance->setName('app:sync-data');

        return $instance;
    }
}
