<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxkJmX8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxkJmX8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCxkJmX8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCxkJmX8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCxkJmX8\App_KernelDevDebugContainer([
    'container.build_hash' => 'CxkJmX8',
    'container.build_id' => 'ee6cfbbe',
    'container.build_time' => 1729083431,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCxkJmX8');
