<?php

namespace ContainerXGSuTCo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IOHaKvbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IOHaKvb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IOHaKvb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'certidao' => ['privates', '.errored..service_locator.IOHaKvb.App\\Entity\\CdaSupp', NULL, 'Cannot autowire service ".service_locator.IOHaKvb": it references class "App\\Entity\\CdaSupp" but no such service exists.'],
        ], [
            'certidao' => 'App\\Entity\\CdaSupp',
        ]);
    }
}
