#nelmio_cors:
    #defaults:
        #origin_regex: true  # Permite usar regex para definir as origens permitidas
        #allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']  # Permite definir origens via variáveis de ambiente
        #allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']  # Métodos HTTP permitidos
        #allow_headers: ['Content-Type', 'Authorization']  # Cabeçalhos permitidos nas requisições
        #expose_headers: ['Link']  # Cabeçalhos que podem ser expostos à aplicação
        #max_age: 3600  # Tempo máximo em segundos para o navegador armazenar a resposta de pré-verificação
    #paths:
        #'^/': null  # Aplicar as regras a todas as rotas
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:4200']  # Adicione seu frontend aqui
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['http://localhost:4200']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Link']
        '^/export/': # Assegure-se de incluir esta rota
            allow_origin: ['http://localhost:4200']
            allow_methods: ['GET', 'OPTIONS'] # Adicione OPTIONS se necessário
            allow_headers: ['Content-Type', 'Authorization']