<?php

namespace ContainerNoTkKOW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCdaSuppService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IOHaKvb.App\Entity\CdaSupp' shared service.
     *
     * @return \App\Entity\CdaSupp
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IOHaKvb": it references class "App\\Entity\\CdaSupp" but no such service exists.');
    }
}
