<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxtvks2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxtvks2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWxtvks2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWxtvks2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWxtvks2\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wxtvks2',
    'container.build_id' => 'e8d9b90e',
    'container.build_time' => 1728670577,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxtvks2');
